### ISSUE TITLE
TF Copper ore doesn't drop

### ISSUE THREAD

**Issue by ghost** [mallrat208/UBC-Ore-Registrar#27]
With latest Thermal Foundation release (2.0.3.77), Migmatite Copper ore doesn't seem to drop at all. Don't know wether its a bug related to TF or UBC Ore Registrar.

**Comment by mallrat208** [comment]
It's not TF or UBC Ore Registrar, there's something odd going on with UBC itself.

**Comment by mallrat208** [comment]
I may just pull the mod for now as there are enough bugs that it's just not worth having to deal with the problems.

Further Research on the problem. It's only affecting blocks that have a a meta value. Ores that do not, such as SG Crafts Naquadah, are fine. they drop what they should.

When you break an ore that would have a meta value, you get this plastered to the log...

```
[00:52:47] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=type, clazz=class cofh.thermalfoundation.block.BlockOre$Type, values=[COPPER, TIN, SILVER, LEAD, ALUMINUM, NICKEL, PLATINUM, IRIDIUM, MITHRIL]} as it does not exist in BlockStateContainer{block=ubcores:igneous_stone_tile.thermalfoundation.ore.platinum.name, properties=[type]}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=type, clazz=class cofh.thermalfoundation.block.BlockOre$Type, values=[COPPER, TIN, SILVER, LEAD, ALUMINUM, NICKEL, PLATINUM, IRIDIUM, MITHRIL]} as it does not exist in BlockStateContainer{block=ubcores:igneous_stone_tile.thermalfoundation.ore.platinum.name, properties=[type]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196) ~[art$a.class:?]
	at cofh.thermalfoundation.block.BlockOre.func_180651_a(BlockOre.java:88) ~[BlockOre.class:?]
	at exterminatorjeff.undergroundbiomes.common.block.UBOre.func_180651_a(UBOre.java:117) ~[UBOre.class:?]
	at exterminatorjeff.undergroundbiomes.common.block.UBOre.getDrops(UBOre.java:136) ~[UBOre.class:?]
	at net.minecraft.block.Block.func_180653_a(Block.java:544) ~[akf.class:?]
	at net.minecraft.block.Block.func_176226_b(Block.java:537) ~[akf.class:?]
	at net.minecraft.block.Block.func_180657_a(Block.java:712) ~[akf.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:336) ~[lv.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:248) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:642) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
```

**Comment by mallrat208** [comment]
I'm closing this issue and moving to #28
