### ISSUE TITLE
Meta-Ores Submitted to UBC don't drop

### ISSUE THREAD

**Issue by mallrat208** [mallrat208/UBC-Ore-Registrar#28]
Ores that are defined by block and meta are currently not dropping.  Ores without meta value and that doesn't share it's block with any other sub blocks work fine, such as Embers' Copper, Lead, and Silver or SG Craft's Naquadah. Most ores are defined by a block and meta value to reduce block usage.

```
[00:52:47] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=type, clazz=class cofh.thermalfoundation.block.BlockOre$Type, values=[COPPER, TIN, SILVER, LEAD, ALUMINUM, NICKEL, PLATINUM, IRIDIUM, MITHRIL]} as it does not exist in BlockStateContainer{block=ubcores:igneous_stone_tile.thermalfoundation.ore.platinum.name, properties=[type]}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=type, clazz=class cofh.thermalfoundation.block.BlockOre$Type, values=[COPPER, TIN, SILVER, LEAD, ALUMINUM, NICKEL, PLATINUM, IRIDIUM, MITHRIL]} as it does not exist in BlockStateContainer{block=ubcores:igneous_stone_tile.thermalfoundation.ore.platinum.name, properties=[type]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196) ~[art$a.class:?]
	at cofh.thermalfoundation.block.BlockOre.func_180651_a(BlockOre.java:88) ~[BlockOre.class:?]
	at exterminatorjeff.undergroundbiomes.common.block.UBOre.func_180651_a(UBOre.java:117) ~[UBOre.class:?]
	at exterminatorjeff.undergroundbiomes.common.block.UBOre.getDrops(UBOre.java:136) ~[UBOre.class:?]
	at net.minecraft.block.Block.func_180653_a(Block.java:544) ~[akf.class:?]
	at net.minecraft.block.Block.func_176226_b(Block.java:537) ~[akf.class:?]
	at net.minecraft.block.Block.func_180657_a(Block.java:712) ~[akf.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:336) ~[lv.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:248) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:642) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
```

This is the same error as #27

**Comment by mallrat208** [comment]
My best guess is that UBC is trying to apply the UBC Ore's blockstate to the underlying Ore Block and causing an exception since it's being fed garbage data. It looks like it should attempt to get the state based off of the Blocks Meta value and act off of that instead

**Comment by mallrat208** [comment]
I've opened an [issue](https://github.com/Zeno410/UndergroundBiomesConstructs1.10/issues/5) with what I think is the problem over at UBC's issue tracker

**Comment by bookerthegeek** [comment]
@mallrat208 you on discord or irc anywhere?

**Comment by mallrat208** [comment]
The most likely place to get me is on discord during the day, my cell connection didn't like IRC, I'm on a few servers, the most notable one is the FTB Reddit server

**Comment by bookerthegeek** [comment]
Kk, I got a couple questions for you. See you this weekend.

**Comment by notfood** [comment]
I happen to have this issue. Any workaround? I'll have to disable UBC ore registrar otherwise.

**Comment by bookerthegeek** [comment]
@notfood not till UBC updates, or you can compile a version with the fix yourself.

**Comment by mallrat208** [comment]
This should be fixed as of the current version of UBC
