### ISSUE TITLE
Caught exception from UBC Ore Registrar

### ISSUE THREAD

**Issue by TomberWolf** [mallrat208/UBC-Ore-Registrar#30]
Minecraft 1.10.2

`Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from UBC Ore Registrar (ubcores)
Caused by: java.lang.IllegalArgumentException: The name ubcores:igneous_stone_ore has been registered twice, for Block{ubcores:igneous_stone_ore} and Block{null}.
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:458)
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.register(FMLControlledNamespacedRegistry.java:829)
	at net.minecraftforge.fml.common.registry.GameData.register_impl(GameData.java:254)
	at net.minecraftforge.fml.common.registry.GameRegistry.register(GameRegistry.java:153)
	at exterminatorjeff.undergroundbiomes.intermod.OreEntry.doRegister(OreEntry.java:48)
	at exterminatorjeff.undergroundbiomes.api.names.Entry.register(Entry.java:60)
	at exterminatorjeff.undergroundbiomes.intermod.OresRegistry.createOre(OresRegistry.java:138)
	at exterminatorjeff.undergroundbiomes.intermod.OresRegistry.setupOre(OresRegistry.java:160)
	at com.mr208.UBCOres.UBCHelper.registerOreBlock(UBCHelper.java:11)
	at com.mr208.UBCOres.UBCHelper.registerModOresWithMeta(UBCHelper.java:33)
	at com.mr208.UBCOres.Mods.ArsMagica2(Mods.java:50)
	at com.mr208.UBCOres.CommonProxy.onPreInit(CommonProxy.java:18)
	at com.mr208.UBCOres.ClientProxy.onPreInit(ClientProxy.java:11)
	at com.mr208.UBCOres.UBCOres.preInit(UBCOres.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:552)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

**Comment by mallrat208** [comment]
This is actually an issue with Underground Biomes Construct itself. It's [not registering blocks with unique registry names](https://github.com/Zeno410/UndergroundBiomesConstructs1.10/issues/4). 

Currently the only means to fix this on my end is to disable one of the of the modes that use 'ore' as their block name.

**Comment by TomberWolf** [comment]
I found out that it's Ars Magica 2 that causes this issue.
Do you have a clue how to prevent this?

**Comment by bookerthegeek** [comment]
No fix till UBC updates....

Or somebody makes a fork.

**Comment by TomberWolf** [comment]
Okay. So... we have to wait.
Thanks for responding. :-)

**Comment by foxfirecodes** [comment]
Ah, have the same issue. Hopefully Zeno can fix this quickly! It's sad, I was hoping to add this mod to my pack. I'm trying to find which of my mods are causing the name-conflicts, and hopefully I can get by with some of them disabled in UBC Ores Registrar.
