### ISSUE TITLE
Crash on newest UBC Update

### ISSUE THREAD

**Issue by bookerthegeek** [mallrat208/UBC-Ore-Registrar#31]
[Crash Report][1] & [Startup Log][2] with the new version of UBC. Changelog said he fixed the issue with ore with the same name.

[1]:https://gist.github.com/bookerthegeek/102845a928b9d696065b9d5a9e1befaa
[2]:https://gist.github.com/bookerthegeek/fcef1e59af6a7b9238112f4e510db47c

**Comment by mallrat208** [comment]
I'm poking around with it now.

The from what I can tell the crash itself is still on UBC. It's changed to using the blocks unlocalized name to be used for it's registry name for all blocks.

This works... kind of.

for example all IE ore blocks actually have the SAME unlocalized name ... tile.immersiveengineering.ore .. IE is however smart enough to return it's unlocalized name + the name of the blockstate. It looks like Ars Magica 2 doesnt and I'm willing to bet a few others don't as well.

**Comment by bookerthegeek** [comment]
Gotcha, I removed Ars from the pack, I'll try again and see what happens.

**Comment by mallrat208** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293503-underground-biomes-constructs?page=82#c1627

So It's fixable, just not on my end.

**Comment by bookerthegeek** [comment]
God Damn that is pretty! To bad it crashed when an ore blew up. Don't know if you or UBC proper.

```
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=resource, clazz=class forestry.core.blocks.EnumResourceType, values=[APATITE, COPPER, TIN]} as it does not exist in BlockStateContainer{block=ubcores:igneous_stone_tile.for.resources.tin, properties=[type]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
	at forestry.core.blocks.BlockResourceOre.func_176201_c(BlockResourceOre.java:62)
	at forestry.core.blocks.BlockResourceOre.func_180651_a(BlockResourceOre.java:111)
	at exterminatorjeff.undergroundbiomes.common.block.UBOre.func_180651_a(UBOre.java:117)
	at exterminatorjeff.undergroundbiomes.common.block.UBOre.getDrops(UBOre.java:136)
	at net.minecraft.block.Block.func_180653_a(Block.java:544)
	at net.minecraft.world.Explosion.func_77279_a(Explosion.java:230)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1176)
	at net.minecraft.world.World.func_72876_a(World.java:2303)
	at aquacreeper.entities.EntityAquaCreeper.waterExplosion(EntityAquaCreeper.java:234)
	at aquacreeper.entities.EntityAquaCreeper.func_70071_h_(EntityAquaCreeper.java:185)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
```
Full crash report [here](https://gist.github.com/bookerthegeek/854c69035c2d2d3571229cd0f2de88ed)

**Comment by mallrat208** [comment]
That's UBC and directly related to the second part of my last post on the minecraftforum's post for UBC

**Comment by bookerthegeek** [comment]
Gotcha. Ok, now to wait on him again.
